---
pre_release_checks:
  - clean_git
steps:
  - script:
      content: echo "Testing Release for $VERSION"
  - script:
      content: echo "releasing $VERSION"
  - hide_dev_dependencies
  - git_add:
      paths:
        - Package.swift
  - unhide_dev_dependencies
