language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      script:
        - swift test
        - swift build --disable-sandbox -c release
        - ./.build/release/rocket 1.0.0 --rocket-file .test.yml

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.0
      script:
        - swift test
        - swift build --disable-sandbox -c release
        - ./.build/release/rocket 1.0.0 --rocket-file .test.yml
